services:
  - type: web
    name: student-registration-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.6
      - key: SECRET_KEY
        generateValue: true
